queue: "Hosted VS2017"
variables: 
  BuildConfiguration: Release
steps:
- task: BatchScript@1
  inputs:
    filename: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\Common7\\Tools\\VsDevCmd.bat"
    arguments: -no_logo
    modifyEnvironment: true
  displayName: Setup Environment Variables

- powershell: |
    # Restore
    msbuild /t:restore SignService.sln 

    # Copy sdk files locally before build
    msbuild src/SignService/SignService.csproj /t:PrebuildScript /p:Configuration=$(BuildConfiguration)

    # Build service
    msbuild src/SignService/SignService.csproj /t:Publish /p:Configuration=$(BuildConfiguration)

    # Build & Publish Cloud Service
    msbuild src/SignServiceCloudService/SignServiceCloudService.ccproj /t:Publish /p:Configuration=$(BuildConfiguration) /p:OutputPath=$(Build.ArtifactStagingDirectory)\ 
  displayName: Build / Publish Service

- powershell: |
    $file = "ServiceConfiguration.Cloud.cscfg"

    # Read file
    $content = Get-Content -Path $file

    # substitute values
    $content = $content.Replace("ABCDEF01234567ABCDEF01234567ABCDEF012345", "__SslCertificateSha1__")

    # Save
    [System.IO.File]::WriteAllText($file, $content)
  displayName: Tokenize certificate fields in cscfg
  workingDirectory: $(Build.ArtifactStagingDirectory)\app.publish

#- task: PublishBuildArtifacts@1
- task: 2FF763A7-CE83-4E1F-BC89-0AE63477CEBE@1
  displayName: Publish SignService Artifact
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)\app.publish
    artifactType: container
    artifactName: SignService